services:
  # --- Kafka: Motor de mensajería Oficial de Apache (KRaft mode) ---
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=INTERNAL://:9092,EXTERNAL://:29092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      # Estabilidad para Cluster de 1 solo Nodo
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      # Optimización JVM para baja memoria
      - KAFKA_HEAP_OPTS=-Xmx800M -Xms800M
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - flights_net

  # --- ClickHouse: Base de Datos Analítica (OLAP) ---
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_DB=flights
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=admin
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    deploy:
      resources:
        limits:
          memory: 1500M
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - flights_net

  # --- Prometheus: Monitorización ---
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=7d'
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - flights_net

  # --- Grafana: Visualización ---
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - flights_net
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning

networks:
  flights_net:
    driver: bridge

volumes:
  clickhouse_data:
  kafka_data:
