apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: ef9a3d1zo8hs0c
    url: http://clickhouse:8123
    access: proxy
    user: admin
    secureJsonData:
      password: admin
    jsonData:
      defaultDatabase: flights
      port: 8123
      server: clickhouse
      username: admin
      protocol: http
    isDefault: true
    editable: true
