name: 'flights_analytics'
version: '1.0.0'
config-version: 2

profile: 'flights_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  flights_analytics:
    # Configurar materialización por defecto
    staging:
      +materialized: view
    marts:
      +materialized: table
      silver:
        +materialized: table
      gold:
        +materialized: table
