{
 "title": "✈️ Flight Analysis Dashboard",
 "tags": [
  "flights",
  "analytics"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Flights",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT count() FROM flights.flights_raw WHERE FlightDate >= toDate($__from/1000) AND FlightDate <= toDate($__to/1000)"
    }
   ]
  },
  {
   "title": "Avg Delay (Min)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "rawSql": "SELECT avg(DepDelay) FROM flights.flights_raw WHERE DepDelay > 0 AND FlightDate >= toDate($__from/1000) AND FlightDate <= toDate($__to/1000)"
    }
   ]
  },
  {
   "title": "Cancellation Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT (countIf(Cancelled = 1) * 100 / count()) FROM flights.flights_raw WHERE FlightDate >= toDate($__from/1000) AND FlightDate <= toDate($__to/1000)"
    }
   ]
  },
  {
   "title": "Daily Traffic Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT toStartOfDay(FlightDate) as time, count() as flights FROM flights.flights_raw WHERE FlightDate >= toDate($__from/1000) AND FlightDate <= toDate($__to/1000) GROUP BY time ORDER BY time"
    }
   ]
  },
  {
   "title": "Top Airlines (Total Flights)",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT Airline, count() as Total FROM flights.flights_raw WHERE FlightDate >= toDate($__from/1000) AND FlightDate <= toDate($__to/1000) GROUP BY Airline ORDER BY Total DESC LIMIT 10"
    }
   ]
  }
 ]
}